##############################
# Netlify configuration file #
##############################

# List of Build plugins
[[plugins]]
# Use the current plugin in builds for testing and debugging.
# Local path to the plugin.
package = "."
  # Plugin configuration
   [plugins.inputs]
   url = "https://c19.division.film/"

[build]
# Dummy build command
command = "echo onBuild"
